### PR TITLE
Convert stream to string

### PR DESCRIPTION
**Pull request by cevou**
When using PostGIS a stream is returned from the database call. This needs to be converted to a string to be processed by the buffer

### CODE REVIEW

**Comment by BenMorel** [comment]
This should be done further up in the call stack: is this resource coming from `DatabaseEngine::queryGeometry()`? In that case, the conversion would be better suited there!

**Comment by cevou** [comment]
Can this also be merged?

**Comment by BenMorel** [comment]
Sorry, I missed your second commit! Merged now.

**Comment by cevou** [comment]
Thanks!

**Pull request merged**
