### PR TITLE
Exclude non relevant files from code coverage

### PR DESCRIPTION
**Pull request by cevou**

### CODE REVIEW

**Comment by BenMorel** [comment]
Isn't it better to just whitelist `src`?

**Comment by BenMorel** [comment]
`<whitelist>` [does work](https://coveralls.io/builds/1796929), along with `processUncoveredFilesFromWhitelist` to ensure that all files are taken into account, even the ones we wouldn't have written tests for yet.

But now the problem is, Coveralls reports do not aggregate all builds, and show poor coverage (~30%) because each build targets different code parts.

If you know a way to make it report the correct coverage across all builds, let me know!

**Comment by cevou** [comment]
You might want to remove the repo from coveralls and add it again. I haven't tried it, but I guess this is the only way to do it.

**Comment by BenMorel** [comment]
What makes you think this?

**Comment by cevou** [comment]
I guess all data is removed if you remove the repo from coveralls. It you enable it again you should be able to start over. Its stange anyway, that coveralls keeps files which aren't part of the code coverage scope anymore.

**Comment by BenMorel** [comment]
I haven't seen files not part of the code coverage, can you point me to them?
My current issue is that each job (MYSQL, PGSQL, etc.) covers different parts of the code, and as far as I can see there is no way to get the aggregate coverage across *all* jobs in Coveralls...

**Comment by cevou** [comment]
Sorry, I had a look at an old report, which still included the files that are now excluded.
There is a section in the coveralls PHP documentation (https://github.com/satooshi/php-coveralls#coverallsyml) which descripes how to merge multiple coverage report files, but this only works, if the job is run on the same machine. The .travis.yml could be changed in a way, that all tests for all engines are run on one machine. This could be achived by calling the phpunit script multiple times in the script section with different env variables.

**Comment by BenMorel** [comment]
Thanks for the pointer, indeed I would need to merge tests for all 4 engines in a single job, so we would only have 3 jobs left : PHP 5.5, PHP 5.6, HHVM.

It might make it harder to spot issues when a test fails on a single engine, though. I'm going to think twice about it before following that route.

It's unfortunate that (as far as I can see) Coveralls does not have a built-in coverage report merge tool to aggregate all the reports received by the different jobs!

**Pull request closed without merging**
